FROM webdevops/php-dev:8.1 AS base

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf \
    build-essential \
    firebird-dev \
    g++ \
    gcc \
    gdb \
    git \
    lcov \
    libicu-dev \
    libtool \
    libxml2-dev \
    make \
    re2c \
    unzip \
    valgrind \
    tzdata \
    vim \
    wget \
    bison \
    && ln -s /usr/lib/x86_64-linux-gnu/libfbclient.so /usr/lib/libfbclient.so \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*



# Set up entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php", "-a"]
