FROM php:8.4-cli AS base

# Install development dependencies
RUN apt-get update && apt-get install -y \
    autoconf \
    build-essential \
    gcc \
    g++ \
    make \
    libtool \
    bison \
    re2c \
    libicu-dev \
    libxml2-dev \
    git \
    unzip \
    wget \
    tzdata \
    vim \
    firebird-dev \
    gdb \
    valgrind \
    lcov \
    cppcheck \
    clang-tidy \
    bear \
    python3-pip \
    libasan8 \
    libubsan1 \
    libtsan2 \
    llvm \
    && ln -s /usr/lib/x86_64-linux-gnu/libfbclient.so /usr/lib/libfbclient.so \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pcntl

# Set up entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php", "-a"]
