FROM php:8.5-rc-cli AS base

# Install development dependencies
RUN apt-get update && apt-get install -y \
    autoconf \
    build-essential \
    gcc \
    g++ \
    make \
    libtool \
    bison \
    re2c \
    libicu-dev \
    libxml2-dev \
    git \
    unzip \
    wget \
    tzdata \
    vim \
    firebird-dev \
    gdb \
    valgrind \
    lcov \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Build and enable Xdebug from source
RUN set -eux; \
    git clone --depth 1 https://github.com/xdebug/xdebug.git /usr/src/xdebug; \
    cd /usr/src/xdebug; \
    phpize; \
    ./configure --enable-xdebug; \
    make -j"$(nproc)"; \
    make install; \
    docker-php-ext-enable xdebug; \
    cd /; \
    rm -rf /usr/src/xdebug

# Copy XDebug runtime configuration (mode, client, etc.)
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# Set up entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php", "-a"]
