--TEST--
Issue #130: fbird_last_insert_id() or normalized RETURNING support
--SKIPIF--
<?php include("skipif.inc"); ?>
--FILE--
<?php
require("firebird.inc");

$conn = fbird_connect($test_base, $user, $password);

fbird_query($conn, "CREATE TABLE test_id (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, val VARCHAR(10))");
fbird_commit($conn);

echo "Inserting row using IDENTITY...\n";
fbird_query($conn, "INSERT INTO test_id (val) VALUES ('test')");

echo "Checking if fbird_last_insert_id() exists...\n";
if (function_exists('fbird_last_insert_id')) {
    $id = fbird_last_insert_id($conn);
    echo "OK: last_insert_id is $id\n";
} else {
    echo "Current behavior: fbird_last_insert_id() does NOT exist\n";
}

fbird_close($conn);
?>
--EXPECTF--
Inserting row using IDENTITY...
Checking if fbird_last_insert_id() exists...
Current behavior: fbird_last_insert_id() does NOT exist
