--TEST--
Issue #130: fbird_last_insert_id() or normalized RETURNING support
--SKIPIF--
<?php include("skipif.inc"); ?>
--FILE--
<?php
require("firebird.inc");

$conn = fbird_connect($test_base, $user, $password);

$tr = fbird_trans($conn);
fbird_query($tr, "RECREATE TABLE test_id (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, val VARCHAR(10))");
fbird_commit($tr);

echo "Inserting row using IDENTITY...\n";
$tr = fbird_trans($conn);
fbird_query($tr, "INSERT INTO test_id (val) VALUES ('test')");
fbird_commit($tr);

echo "Checking if fbird_last_insert_id() exists...\n";
var_dump(function_exists('fbird_last_insert_id'));

/* fbird_last_insert_id requires a sequence name — Firebird has no implicit last-insert-id */
echo "Without sequence name (should warn):\n";
$id = @fbird_last_insert_id($conn);
var_dump($id);

/* Use the identity column's underlying generator */
$tr = fbird_trans($conn);
$rs = fbird_query($tr, "SELECT RDB\$GENERATOR_NAME FROM RDB\$RELATION_FIELDS WHERE RDB\$RELATION_NAME = 'TEST_ID' AND RDB\$IDENTITY_TYPE IS NOT NULL");
$row = fbird_fetch_assoc($rs);
$gen_name = trim($row['RDB$GENERATOR_NAME']);
fbird_free_result($rs);
fbird_commit($tr);

echo "Generator: $gen_name\n";
$val = fbird_last_insert_id($conn, $gen_name);
echo "last_insert_id: $val\n";

$tr = fbird_trans($conn);
fbird_query($tr, "DROP TABLE test_id");
@fbird_commit($tr);
fbird_close($conn);
echo "Done\n";
?>
--EXPECTF--
Inserting row using IDENTITY...
Checking if fbird_last_insert_id() exists...
bool(true)
Without sequence name (should warn):
bool(false)
Generator: %s
last_insert_id: 1
Done

--CLEAN--
<?php require_once __DIR__ . '/clean.inc'; ?>
