--TEST--
fbird_query($conn, $sql) autocommit sees committed data (Issue #294)
--EXTENSIONS--
firebird
--SKIPIF--
<?php include("skipif.inc"); ?>
--FILE--
<?php
require("firebird.inc");

/*
 * Regression test for GitHub Issue #294:
 *   fbird_query($connection, $sql) in autocommit mode doesn't see data
 *   committed by active transaction (v11.0.1)
 *
 * Root cause:
 *   _php_fbird_def_trans() caches a SNAPSHOT-isolation transaction in
 *   ib_link->tr_list->trans and reuses it across all fbird_query($conn, ...)
 *   calls without ever committing or restarting it. The snapshot is frozen
 *   at the time of the first query, so data committed by OTHER transactions
 *   after that point is invisible.
 *
 *   PHP_FUNCTION(fbird_query) does not commit/restart the default transaction
 *   after _php_fbird_exec() returns, so the stale snapshot persists.
 *
 * Fix:
 *   True autocommit: after _php_fbird_exec() returns for the implicit/default
 *   transaction path, commit the default transaction and nullify
 *   tr->fbt_transaction so the next fbird_query($conn, ...) starts a fresh
 *   transaction with a current snapshot.
 *
 * Reproduction flow:
 *   1. Start the default tx via an initial autocommit query (snapshot at t1)
 *   2. Do DDL + INSERT in an explicit tx, commit (data committed at t2 > t1)
 *   3. fbird_query($conn, $query) autocommit — REUSES stale default tx (t1)
 *      Before fix: returns no rows (stale snapshot)
 *      After fix: returns the generator name (fresh snapshot)
 *   4. fbird_query($tx, $query) explicit — fresh snapshot, always works
 */

$conn = fbird_connect($test_base);
if (!$conn) {
    die("FAIL: connect failed: " . fbird_errmsg() . "\n");
}

// Step 1: Start the default transaction with an initial autocommit query.
// This freezes the default tx snapshot BEFORE the DDL is committed.
$r0 = fbird_query($conn, 'SELECT 1 FROM RDB$DATABASE');
if (!$r0) {
    die("FAIL: initial query failed: " . fbird_errmsg() . "\n");
}
fbird_free_result($r0);

// Step 2: Create a table in an explicit transaction, then commit.
// (Firebird OO API requires a hard commit between DDL and DML to refresh
//  the metadata cache — see CHANGELOG note for pdo_fbird_ddl2.phpt.)
$tx = fbird_trans($conn);
if (!$tx) {
    die("FAIL: fbird_trans failed: " . fbird_errmsg() . "\n");
}
$r = fbird_query($tx, 'CREATE TABLE LID_TEST_294 (ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, VAL VARCHAR(10))');
if (!$r) {
    die("FAIL: create table failed: " . fbird_errmsg() . "\n");
}
fbird_commit($tx);

// Step 3: Insert a row in a NEW explicit transaction, then commit.
$tx = fbird_trans($conn);
if (!$tx) {
    die("FAIL: fbird_trans #2 failed: " . fbird_errmsg() . "\n");
}
$r = fbird_query($tx, "INSERT INTO LID_TEST_294 (VAL) VALUES ('x')");
if (!$r) {
    die("FAIL: insert failed: " . fbird_errmsg() . "\n");
}
fbird_commit($tx);

// Step 3: Start a NEW explicit transaction (simulates DBAL autoCommit cycle)
$tx = fbird_trans($conn);
if (!$tx) {
    die("FAIL: fbird_trans #2 failed: " . fbird_errmsg() . "\n");
}

// === BUG: autocommit query must see the committed data ===
// The RDB$RELATION_FIELDS query is what doctrine-firebird-driver's
// lastInsertId() uses to resolve IDENTITY generators.
$query = "SELECT FIRST 1 TRIM(RDB\$GENERATOR_NAME) FROM RDB\$RELATION_FIELDS"
       . " WHERE UPPER(TRIM(RDB\$RELATION_NAME)) = 'LID_TEST_294'"
       . " AND RDB\$GENERATOR_NAME IS NOT NULL";

// fbird_query($conn, $sql) -- autocommit, reuses stale default transaction
$r1 = fbird_query($conn, $query);
if (!$r1) {
    die("FAIL: autocommit query failed: " . fbird_errmsg() . "\n");
}
$row1 = fbird_fetch_row($r1);
fbird_free_result($r1);

// fbird_query($tx, $sql) -- uses active transaction (always worked)
$r2 = fbird_query($tx, $query);
if (!$r2) {
    die("FAIL: explicit-tx query failed: " . fbird_errmsg() . "\n");
}
$row2 = fbird_fetch_row($r2);
fbird_free_result($r2);

fbird_commit($tx);

// Both paths must return the same generator name
echo "autocommit: ";
var_dump($row1);
echo "explicit-tx: ";
var_dump($row2);

// Verify the autocommit path sees the data
if ($row1 === false || $row1 === null) {
    echo "FAIL: autocommit query returned no rows (stale snapshot)\n";
} elseif ($row2 !== false && $row2 !== null && $row1[0] === $row2[0]) {
    echo "PASS: autocommit sees committed data\n";
} else {
    echo "FAIL: autocommit and explicit-tx results differ\n";
}

// Also verify the inserted row is visible via autocommit
$tx2 = fbird_trans($conn);
$r3 = fbird_query($conn, "SELECT VAL FROM LID_TEST_294 WHERE VAL = 'x'");
$row3 = fbird_fetch_row($r3);
fbird_free_result($r3);
fbird_commit($tx2);

echo "data-visible: ";
var_dump($row3);
if ($row3 !== false && $row3[0] === 'x') {
    echo "PASS: autocommit sees inserted row\n";
} else {
    echo "FAIL: autocommit cannot see inserted row\n";
}

fbird_close($conn);
echo "Done\n";
?>
--EXPECT--
autocommit: array(1) {
  [0]=>
  string(5) "RDB$1"
}
explicit-tx: array(1) {
  [0]=>
  string(5) "RDB$1"
}
PASS: autocommit sees committed data
data-visible: array(1) {
  [0]=>
  string(1) "x"
}
PASS: autocommit sees inserted row
Done
--CLEAN--
<?php require_once __DIR__ . '/clean.inc'; ?>
