#!/bin/bash
set -e
source "$(dirname "$0")/lib/logging.sh"
source "$(dirname "$0")/lib/detect-firebird.sh"

# This script is meant to be run INSIDE the docker container.
# Example usage from host: docker compose run --rm php84-fb3-dev /ext/scripts/coverage.sh

log_info "Starting Code Coverage generation..."

# Change to extension root
cd /ext

# Clean previous builds/coverage
if [ -f Makefile ]; then
    make clean
    phpize --clean
fi
rm -rf coverage

# 1. Configure with Coverage Flags (GCC/LCOV)
log_info "Configuring build..."
phpize
# Check if coverage flags are supported (standard in this dev container)
export CFLAGS="-fprofile-arcs -ftest-coverage -O0 -g"
export CXXFLAGS="-fprofile-arcs -ftest-coverage -O0 -g"
export LDFLAGS="--coverage"

# Auto-detect Firebird install prefix using shared helper
detect_firebird
FB_PREFIX="$FIREBIRD_PATH"
export CPPFLAGS="-I$FIREBIRD_INCLUDE"

./configure --with-firebird="${FB_PREFIX}"

# 2. Build
log_info "Building extension..."
make -j$(nproc)

# 3. Run Tests
log_info "Running tests..."
export NO_INTERACTION=1
export REPORT_EXIT_STATUS=1
export TEST_PHP_EXECUTABLE=$(which php)
# Use test.sh to ensure: correct extension path, FIREBIRD_HOST env, and recursive tests/coverage/ inclusion
/ext/scripts/test.sh || true # Allow failure, we still want coverage report

# 4. Capture Coverage
log_info "Capturing coverage..."
mkdir -p coverage

# Fix: Copy .gcno files to .libs where .gcda files are generated by libtool
mkdir -p .libs
cp *.gcno .libs/ 2>/dev/null || true

# Capture initial state (ignore errors if some files match but others don't)
lcov --directory . --capture --output-file coverage/lcov.info --ignore-errors path

# 5. Filter Coverage
# Remove system headers, PHP headers, Firebird SDK headers, tests, and build artifacts
log_info "Filtering coverage..."
lcov --remove coverage/lcov.info \
    '/usr/*' \
    '/opt/firebird/*' \
    '*/php-src/*' \
    '*/tests/*' \
    '*/modules/*' \
    '*/.libs/*' \
    --output-file coverage/lcov_filtered.info \
    --ignore-errors unused

# 6. Generate HTML Report
log_info "Generating HTML report..."
genhtml coverage/lcov_filtered.info --output-directory coverage/html

# 7. Print text summary
echo "-----------------------------------------------------------------------"
log_pass "Coverage Report Generated!"
echo ""
log_info "=== Per-file line coverage summary ==="
lcov --summary coverage/lcov_filtered.info 2>&1
echo ""
log_info "=== Detailed per-file breakdown ==="
lcov --list coverage/lcov_filtered.info 2>/dev/null || true
echo ""
log_info "Open coverage/html/index.html in your browser for the full HTML report."
log_info "(standard docker-compose.yml maps ./ to /ext so it appears in ./coverage/html)"
echo "-----------------------------------------------------------------------"
