#!/bin/bash
set -e

# This script is meant to be run INSIDE the docker container.
# Example usage from host: docker compose run --rm php83-dev /ext/docker/scripts/coverage.sh

echo "Starting Code Coverage generation..."

# Change to extension root
cd /ext

# Clean previous builds/coverage
if [ -f Makefile ]; then
    make clean
    phpize --clean
fi
rm -rf coverage

# 1. Configure with Coverage Flags (GCC/LCOV)
echo "Configuring build..."
phpize
# Check if coverage flags are supported (standard in this dev container)
export CFLAGS="-fprofile-arcs -ftest-coverage -O0 -g"
export CXXFLAGS="-fprofile-arcs -ftest-coverage -O0 -g"
export LDFLAGS="--coverage"

./configure --with-firebird=/usr

# 2. Build
echo "Building extension..."
make -j$(nproc)

# 3. Run Tests
echo "Running tests..."
export NO_INTERACTION=1
export REPORT_EXIT_STATUS=1
export TEST_PHP_EXECUTABLE=$(which php)
# We need to ensure the extension is loaded for tests. make test does this by using run-tests.php -d extension=...
make test || true # Allow failure, we still want coverage report

# 4. Capture Coverage
echo "Capturing coverage..."
mkdir -p coverage

# Fix: Copy .gcno files to .libs where .gcda files are generated by libtool
mkdir -p .libs
cp *.gcno .libs/ 2>/dev/null || true

# Capture initial state (ignore errors if some files match but others don't)
lcov --directory . --capture --output-file coverage/lcov.info --ignore-errors path

# 5. Filter Coverage
# Remove system headers, PHP headers, tests, and build artifacts
echo "Filtering coverage..."
lcov --remove coverage/lcov.info \
    '/usr/*' \
    '*/php-src/*' \
    '*/tests/*' \
    '*/modules/*' \
    '*/.libs/*' \
    --output-file coverage/lcov_filtered.info \
    --ignore-errors unused

# 6. Generate HTML Report
echo "Generating HTML report..."
genhtml coverage/lcov_filtered.info --output-directory coverage/html

echo "-----------------------------------------------------------------------"
echo "Coverage Report Generated!"
echo "Open coverage/html/index.html in your browser to view results."
echo "(Note: You may need to copy it out if your volume mapping is different, "
echo " but standard docker-compose.yml maps ./ to /ext so it should appear in ./coverage/html)"
echo "-----------------------------------------------------------------------"
