#!/bin/bash
set -e

# This script is meant to be run INSIDE the docker container.
# Example usage from host: docker compose run --rm php84-fb3-dev /ext/scripts/coverage.sh

echo "Starting Code Coverage generation..."

# Change to extension root
cd /ext

# Clean previous builds/coverage
if [ -f Makefile ]; then
    make clean
    phpize --clean
fi
rm -rf coverage

# 1. Configure with Coverage Flags (GCC/LCOV)
echo "Configuring build..."
phpize
# Check if coverage flags are supported (standard in this dev container)
export CFLAGS="-fprofile-arcs -ftest-coverage -O0 -g"
export CXXFLAGS="-fprofile-arcs -ftest-coverage -O0 -g"
export LDFLAGS="--coverage"

# Auto-detect Firebird install prefix (FB3 uses /opt/firebird, FB4/5 use /usr)
if [ -f /opt/firebird/include/ibase.h ]; then
    FB_PREFIX=/opt/firebird
    export CPPFLAGS="-I/opt/firebird/include"
else
    FB_PREFIX=/usr
fi
echo "Detected Firebird prefix: ${FB_PREFIX}"

./configure --with-firebird="${FB_PREFIX}"

# 2. Build
echo "Building extension..."
make -j$(nproc)

# 3. Run Tests
echo "Running tests..."
export NO_INTERACTION=1
export REPORT_EXIT_STATUS=1
export TEST_PHP_EXECUTABLE=$(which php)
# Use test.sh to ensure: correct extension path, FIREBIRD_HOST env, and recursive tests/coverage/ inclusion
/ext/scripts/test.sh || true # Allow failure, we still want coverage report

# 4. Capture Coverage
echo "Capturing coverage..."
mkdir -p coverage

# Fix: Copy .gcno files to .libs where .gcda files are generated by libtool
mkdir -p .libs
cp *.gcno .libs/ 2>/dev/null || true

# Capture initial state (ignore errors if some files match but others don't)
lcov --directory . --capture --output-file coverage/lcov.info --ignore-errors path

# 5. Filter Coverage
# Remove system headers, PHP headers, Firebird SDK headers, tests, and build artifacts
echo "Filtering coverage..."
lcov --remove coverage/lcov.info \
    '/usr/*' \
    '/opt/firebird/*' \
    '*/php-src/*' \
    '*/tests/*' \
    '*/modules/*' \
    '*/.libs/*' \
    --output-file coverage/lcov_filtered.info \
    --ignore-errors unused,mismatch

# 6. Generate HTML Report
echo "Generating HTML report..."
genhtml coverage/lcov_filtered.info --output-directory coverage/html

# 7. Print text summary
echo "-----------------------------------------------------------------------"
echo "Coverage Report Generated!"
echo ""
echo "=== Per-file line coverage summary ==="
lcov --summary coverage/lcov_filtered.info 2>&1
echo ""
echo "=== Detailed per-file breakdown ==="
lcov --list coverage/lcov_filtered.info 2>/dev/null || true
echo ""
echo "Open coverage/html/index.html in your browser for the full HTML report."
echo "(standard docker-compose.yml maps ./ to /ext so it appears in ./coverage/html)"
echo "-----------------------------------------------------------------------"
