#!/bin/bash
set -e

echo "Testing PHP Firebird extension..."

# Change to extension root directory
cd /ext

# Clean test artifacts from previous runs.
# Two-pass approach:
#   1. Recursive for pure artifact extensions (*.diff, *.out, *.exp, *.log, *.mem)
#      — these are always generated by run-tests.php, never source files.
#   2. Top-level only (-maxdepth 1) for ambiguous extensions (*.php, *.sh)
#      — subdirectories like tests/sanitizer/ contain tracked .php source files.
for dir in tests pdo_fbird/tests; do
    if [ -d "$dir" ]; then
        # Pass 1: recursive for unambiguous artifact extensions
        find "$dir" \
            \( -name '*.diff' -o -name '*.out' -o -name '*.exp' \
               -o -name '*.log' -o -name '*.mem' \) \
            -delete 2>/dev/null || true
        # Pass 2: top-level only for *.php and *.sh (protects source files in subdirs)
        find "$dir" -maxdepth 1 \
            \( -name '*.php' -o -name '*.sh' \) \
            -not -name 'common.inc' -not -name 'config.inc' \
            -not -name 'firebird.inc' -not -name 'functions.inc' \
            -not -name 'skipif.inc' \
            -delete 2>/dev/null || true
    fi
done

# Ensure extension is built and compatible
if [ ! -f modules/firebird.so ]; then
    echo "Extension not found. Building first..."
    /ext/scripts/build.sh
else
    # Check if extension loads successfully (handles API mismatch leftovers)
    if ! php -n -d extension=$(pwd)/modules/firebird.so -r "exit(extension_loaded('firebird') ? 0 : 1);" >/dev/null 2>&1; then
        echo "Extension found but failed to load (possible API mismatch). Rebuilding..."
        /ext/scripts/build.sh
    fi
fi

# Print PHP version and extension information
php -n -d extension=$(pwd)/modules/firebird.so -r "
    echo 'PHP Version: ' . PHP_VERSION . PHP_EOL;
    echo 'Extension loaded: ' . (extension_loaded('firebird') ? 'YES' : 'NO') . PHP_EOL;
    echo 'Extension version: ' . phpversion('firebird') . PHP_EOL;
"

# Run tests if available
if [ -d "tests" ]; then
    echo "Running tests..."
    # Allow an optional argument to restrict the test set (e.g. a single .phpt file
    # or subdirectory). Defaults to running the entire tests/ tree.
    if [ $# -eq 0 ]; then
        TARGET="tests/"
        # Include pdo_fbird tests if they exist
        if [ -d "pdo_fbird/tests" ]; then
            TARGET="$TARGET pdo_fbird/tests/"
        fi
    else
        # Resolve test file arguments to actual paths
        TARGET=""
        for arg in "$@"; do
            resolved=""
            # If argument is already a valid file or directory, use it as-is
            if [ -e "$arg" ]; then
                resolved="$arg"
            # Try tests/ prefix
            elif [ -e "tests/$arg" ]; then
                resolved="tests/$arg"
            # Try adding .phpt extension
            elif [ -e "$arg.phpt" ]; then
                resolved="$arg.phpt"
            # Try tests/ prefix with .phpt extension
            elif [ -e "tests/$arg.phpt" ]; then
                resolved="tests/$arg.phpt"
            # Try pdo_fbird/tests/ prefix
            elif [ -e "pdo_fbird/tests/$arg" ]; then
                resolved="pdo_fbird/tests/$arg"
            elif [ -e "pdo_fbird/tests/$arg.phpt" ]; then
                resolved="pdo_fbird/tests/$arg.phpt"
            else
                echo "Cannot find test file \"$arg\"."
                exit 1
            fi
            TARGET="$TARGET $resolved"
        done
    fi
    # Build extension arguments - load firebird and pdo_fbird separately
    EXT_ARGS="-d extension=$(pwd)/modules/firebird.so"
    if [ -f pdo_fbird/modules/pdo_fbird.so ]; then
        EXT_ARGS="$EXT_ARGS -d extension=$(pwd)/pdo_fbird/modules/pdo_fbird.so"
    fi
    # Check if pcntl is available (needed for fork tests)
    if php -m 2>/dev/null | grep -q pcntl; then
        EXT_ARGS="$EXT_ARGS -d extension=pcntl"
    fi
    TEST_PHP_EXECUTABLE=/usr/local/bin/php TEST_PHP_ARGS="-n" php -n run-tests.php $EXT_ARGS $TARGET
else
    echo "No test directory found. Skipping tests."
fi

echo "Testing complete."
